#!/bin/bash

if [ "$#" -gt 1 ]; then
    echo "Just two arguments are allowed."
    exit 1
fi

if [ "$1" = "0" ]; then
    ssh-add -D
    ssh-add ~/.ssh/anugraha
elif [ "$1" = "1" ]; then
    ssh-add -D
    ssh-add ~/.ssh/resAnugraha
else
    echo 'Could not ready the user.'
fi