#!/bin/bash

function _auto_completion {
    local CURRENT_WORD
    local AVAILABLE_COMMANDS="freshmain rebase"
    CURRENT_WORD="${COMP_WORDS[COMP_CWORD]}"

    if [[ "$COMP_CWORD" -eq 1 ]]; then
        # Generate completions for the "--option" argument
        COMPREPLY=("$(compgen -W "$AVAILABLE_COMMANDS" -- "$CURRENT_WORD")")

    else
        # COMPREPLY=("ls")
        echo "$AVAILABLE_COMMANDS"

        # Default completions for other arguments or options
        # COMPREPLY=('freshMain')
    fi
}

complete -F _auto_completion automate

if [ "$1" = "rebase" ]; then
    git rebase -i HEAD~"$2"
fi

if [ "$1" = "freshmain " ]; then
    git branch -D main && git fetch origin main:main && git checkout main
fi

if [ $# -gt 2 ]; then
    echo "Just two argument is allowed kid"
fi



### dummy example for deployment without CICD

#!/bin/bash

eval "$(ssh-agent -s)" 

ssh-add ~/.ssh/adventure-admin

cd apps/pointstore/api/ || exit

git checkout -b oldMain || echo "proceeding to next step"

git branch -D main || echo "no main branch found proceeding to next step"

git fetch origin main:main && git checkout main 

git branch -D oldMain

npm install 

pm2 stop api

npm run build:prod

if [ $? -ne 0 ]; then

    echo "build failed please resolve build issue"
    pm2 restart api
    exit 

fi

pm2 restart api

if [ $? -eq 0 ]; then

    echo "Deploy successful changes will take effect in about 10 seconds."

    echo "Please exit the session using 'exit' command whenever you are ready."

    echo "Thank You"

fi  


#export PATH=/home/smthsmth:$PATH 