#!/bin/bash

cd apps/pointstore/api/ || exit

git checkout -b oldMain || echo "proceeding to next step"

git branch -D main || echo "no main branch found proceeding to next step"

git fetch origin main:main && git checkout main 

git branch -D oldMain

npx prisma migrate dev

npm install 

npm run runner build.ts 

if [ $? -ne 0 ]; then

    echo "build failed please resolve build issue"
    exit 

fi

npm run seed

pm2 restart api

if [ $? -eq 0 ]; then

    echo "Deploy successful changes will take effect in about 10 seconds."

    echo "Please exit the session using 'exit' command whenever you are ready."

    echo "Thank You"

fi  

